# Generated by Django 5.1.1 on 2024-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alignmenttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmenttask",
            name="plot_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="alignment_results/"
            ),
        ),
    ]
